const HERO_IMAGE_PATH = import.meta.env.VITE_IMAGE_PATH + '/activity/hero';

export const HERO_DATA = [
  // 10기
  {
    name: '나유진',
    batch: 10,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/10기 나유진.png`,
    retro: '대학시절 제일 잘한 일 중 하나, 숙멋♡',
  },
  {
    name: '임아현',
    batch: 10,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/10기 임아현.png`,
    retro: '숙멋에서 만난 소중한 인연들과 만든 첫 웹서비스 ⭐',
  },
  // 11기
  {
    name: '김원희',
    batch: 11,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/11기 김원희.png`,
    retro: '함께 성장할 수 있어 소중한 시간들이었습니다!',
  },
  {
    name: '윤서희',
    batch: 11,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/11기 윤서희.png`,
    retro: '가장 잊지 못할 추억, 가장 잊지 못할 성장',
  },
  {
    name: '이서현',
    batch: 11,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/11기 이서현.png`,
    retro: '숙대에서 경험한 가장 값진 시간',
  },
  {
    name: '이선아',
    batch: 11,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/11기 이선아.png`,
    retro: '멋진 팀원들과 숙명적 만남을 얻어갈 수 있길 어흥~',
  },
  {
    name: '이예지',
    batch: 11,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/11기 이예지.png`,
    retro: '개발의 재미를 알게 해준 대학생활 최고의 선택!',
  },
  {
    name: '조성하',
    batch: 11,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/11기 조성하.png`,
    retro: '성장의 밑거름은 늘 멋대에서, 지금 도전해보세요!',
  },
  // 12기
  {
    name: '강주은',
    batch: 12,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/12기 강주은.png`,
    retro: '최고의 동료들과 치열하게 성장할 수 있는 곳입니다!',
  },
  {
    name: '경민서',
    batch: 12,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/12기 경민서.png`,
    retro: '숙멋만의 방법으로 느끼는 협업의 가치, 함께해요!',
  },
  {
    name: '김보미',
    batch: 12,
    part: '기획/디자인',
    image: `${HERO_IMAGE_PATH}/12기 김보미.png`,
    retro: '숙명에서 가장 성장했던 시간이었습니다!',
  },
  {
    name: '박우현',
    batch: 12,
    part: '기획/디자인',
    image: `${HERO_IMAGE_PATH}/12기 박우현.png`,
    retro: '이론부터 실전까지 한 번에 경험할 수 있는 멋대!',
  },
  {
    name: '서문지',
    batch: 12,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/12기 서문지.png`,
    retro: '플젝 뿐만 아니라 대학 추억까지 만들 수 있는 숙멋!',
  },
  {
    name: '성윤정',
    batch: 12,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/12기 성윤정.png`,
    retro: '아이디어를 서비스로 실현하며 완주의 의미를 배운 경험',
  },
  {
    name: '유동은',
    batch: 12,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/12기 유동은.png`,
    retro: '멋쟁이들과 멋진 프로젝트로 추억도 경험도 가 - 득!',
  },
  {
    name: '이현정',
    batch: 12,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/12기 이현정.png`,
    retro: '개발 실력은 물론 개발 외적으로도 많이 성장했습니다!',
  },

  // 13기
  {
    name: '김민서',
    batch: 13,
    part: '기획/디자인',
    image: `${HERO_IMAGE_PATH}/13기 김민서.png`,
    retro: '숙명인이 된 후 최고의 경험 최고의 열정 최고의 선택',
  },
  {
    name: '김보민',
    batch: 13,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/13기 김보민.png`,
    retro: '많은 것을 배우고, 소중한 인연도 만들 수 있습니다.',
  },
  {
    name: '김은지',
    batch: 13,
    part: '기획/디자인',
    image: `${HERO_IMAGE_PATH}/13기 김은지.png`,
    retro: '아이디어를 현실로 옮긴 소중한 경험이었습니다.',
  },
  {
    name: '박세은',
    batch: 13,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/13기 박세은.png`,
    retro: '멋진 사람과 최고의 겅험을 쌓을 수 있는 숙멋!',
  },
  {
    name: '박소연',
    batch: 13,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/13기 박소연.png`,
    retro: '후회 없는 1년을 만들어준 숙멋, 꼭 도전해 보세요!',
  },
  {
    name: '안성민',
    batch: 13,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/13기 안성민.png`,
    retro: '개발을 사랑하는 사람들과 함께하는 프로젝트 !',
  },
  {
    name: '이경은',
    batch: 13,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/13기 이경은.png`,
    retro: '열정적으로 배우고 경험할 수 있었던 1년이었습니다.',
  },
  {
    name: '이승채',
    batch: 13,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/13기 이승채.png`,
    retro: '열정 가득한 공동체에서 깊이 배우고 성장하였습니다!',
  },
  {
    name: '이연서',
    batch: 13,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/13기 이연서.png`,
    retro: '숙명에서의 선택들 중 가장 최고의 선택은 숙멋이었어요!',
  },
  {
    name: '이채빈',
    batch: 13,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/13기 이채빈.png`,
    retro: '멋사에서의 다양한 경험으로 한층 성장할 수 있었습니다!',
  },
  {
    name: '이혜지',
    batch: 13,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/13기 이혜지.png`,
    retro: '팀원들과 밤낮없이 달린 숙명에서 가장 뜨거웠던 순간🔥',
  },
  {
    name: '정교은',
    batch: 13,
    part: '프론트엔드',
    image: `${HERO_IMAGE_PATH}/13기 정교은.png`,
    retro: '매사에 진심인 사람들과 함께한 숙명에서의 최고의 경험',
  },
  {
    name: '최서아',
    batch: 13,
    part: '백엔드',
    image: `${HERO_IMAGE_PATH}/13기 최서아.png`,
    retro: '1년 중 가장 값지고 유익한 시간을 보냈습니다!',
  },
  {
    name: '하지민',
    batch: 13,
    part: '기획/디자인',
    image: `${HERO_IMAGE_PATH}/13기 하지민.png`,
    retro: '숙멋 모두 함께라서 가능했던 도전과 성장의 시간이었습니다!',
  },
];
