const THIRTEENTH_PROJECT_IMAGE_PATH = import.meta.env.VITE_IMAGE_PATH + '/project/13th';

export const thirteenthProjectsData = [
  {
    id: '1300',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/neonnaekkeoGYM.png`,
    title: '넌내꺼짐',
    teamMember: '하지민(PM)\n박소연(FE), 이승채(FE)\n안성민(BE), 이혜지(BE)',
    summary: '기구 앞 눈치싸움에서 벗어나는 가장 똑똑한 방법',
    description:
      '헬스장 및 기구별 혼잡도와 개인 운동 루틴을 고려해, AI가 효율적인 기구 사용 순서를 자동으로 배정하여 운동 흐름이 끊기지 않도록 돕는 헬스장 배정 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1CFuPEeZwHHMtR4-XNJSfcY7JZwjsTu-U/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '아이디어톤',
    techStack: '-',
    award: null,
  },
  {
    id: '1301',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/balpyoHAI.png`,
    title: '발표HAI',
    teamMember: '김은지(PM)\n이채빈(FE), 정교은(FE)\n김보민(BE)',
    summary: '발표가 두려운 순간, 당신만을 위한 AI 발표 튜터',
    description:
      '발표HAI는 발표가 두려운 학생을 위한 AI 발표 튜터링 서비스입니다. 발표 유형별 맞춤 분석과 실시간 피드백으로 제공하여 발표 흐름과 전달력을 개선에 도움을 줍니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1EwiAyHiHS88qwNwXx7KmXgm5GQbH1sF9/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '아이디어톤',
    techStack: '-',
    award: null,
  },
  {
    id: '1302',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/wearther.png`,
    title: 'WEARTHER',
    teamMember: '김민서(PM)\n박세은(FE), 이연서(FE)\n이경은(BE), 최서아(BE)',
    summary: '나만의 날씨 기반 코디네이터',
    description:
      '실제 내 옷장의 아이템을 기반으로 유저의 취향/상황과 현재 날씨에 맞게 코디를 추천해주는 AI 코디네이터 서비스',
    googleDriveUrl: 'https://drive.google.com/file/d/1Dt4xmoeZVs8Ay4J3xj8L146fMnWjqEyT/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '아이디어톤',
    techStack: '-',
    award: null,
  },
  {
    id: '1303',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/spotal.png`,
    title: 'Spotal',
    teamMember: '하지민(PM)\n박세은(FE), 이연서(FE)\n김보민(BE), 안성민(BE)\n최서아(BE)',
    summary: '가게의 흔적과 기억을 연결하는 동네의 감성 기록장',
    description:
      '재개발로 사라진 동네 가게와 그에 얽힌 기억을 기록하고,\n사용자의 감성을 기준으로 유사한 새로운 공간을 연결해주는 AI 기반 장소 아카이빙 서비스입니다.\n잊힌 공간의 이야기를 보존하며, 단골과 동네 상권을 다시 이어줍니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1z3DW2ZiMCGFkeYnb5WE6VbZ2KHPBOSNL/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/Likelion-at-SMWU-13th/Spotal-BE',
    gitFeUrl: 'https://github.com/Likelion-at-SMWU-13th/Spotal-FE',
    no: '13기',
    category: '중앙해커톤',
    techStack: 'Django, React(JavaScript)',
    award: null,
  },
  {
    id: '1304',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/gorugoru.png`,
    title: 'GoruGoru',
    teamMember: '김은지(PM)\n박소연(FE), 정교은(FE)\n이경은(BE), 이혜지(BE)',
    summary: '외국인 여행객과 상인을 이어주는 다국어 전통시장 탐방 플랫폼',
    description:
      '언어와 정보의 장벽으로 접근이 어려웠던 전통시장을 외국인 여행객이 쉽게 이해하고 탐방할 수 있도록 돕는 서비스입니다.\n상점 정보와 코스 추천을 통해 이용 맥락을 직관적으로 제공해 전통시장 이용 경험을 확장하고, 여행객과 상인 간의 자연스러운 교류를 만들어냅니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1QQ28vVPt_eIh-LNXjo8uJRzdG5HZZunh/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/Likelion-at-SMWU-13th/OnDongNae-Server',
    gitFeUrl: 'https://github.com/Likelion-at-SMWU-13th/OnDongNae-Client',
    no: '13기',
    category: '중앙해커톤',
    techStack: 'Django, React(JavaScript)',
    award: null,
  },
  {
    id: '1305',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/tumblerin.png`,
    title: '텀블러인',
    teamMember: '김민서(PM)\n이승채(FE), 이채빈(FE)\n서문지(BE), 이현정(BE), 홍상희(BE)',
    summary: '함께 만드는 우리 동네 텀블러 문화',
    description:
      '텀블러인은 우리 동네 카페와 함께 텀블러 이용 문화를 확산하는 친환경 서비스입니다. 텀블러 혜택 카페 정보와 맞춤형 추천을 제공하고, 텀블러 인증을 통해 스탬프·포인트 적립과 할인 혜택을 받을 수 있도록 합니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1-kGrarxELvMYl43lTdtWIvD6pDvUfCxS/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/Likelion-at-SMWU-13th/Tumbloom-BE',
    gitFeUrl: 'https://github.com/Likelion-at-SMWU-13th/Tumbloom-FE',
    no: '13기',
    category: '중앙해커톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1306',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/cooltime.png`,
    title: '쿨타임',
    teamMember: '박세은(FE), 이연서(FE) 외 3명',
    summary: '미룸을 기록하고 나를 이해하는 회복형 서비스',
    description:
      '쿨타임(COOLTIME)은 미룸(지연행동)을 기록해 원인과 패턴을 파악하고, 유형 테스트와 AI 주간 레포트로 맞춤 피드백을 제공해 자기 회복을 돕는 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1_4nfDTBxk4lRTfEikidfs6B3VaOKiqiN/view?usp=sharing',
    gitOrgUrl: 'https://github.com/4LINETHON-Team1',
    gitBeUrl: null,
    gitFeUrl: 'https://github.com/4LINETHON-Team1/Cooltime-FE',
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1307',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/plink.png`,
    title: 'PLINK',
    teamMember: '안성민(BE), 최서아(BE) 외 4명',
    summary: '축제의 지루한 대기 시간을 함께 즐기는 놀이(Play)로 연결(Link)하는 서비스',
    description:
      'PLINK는 축제에서 지루한 기다림 시간을 즉각적인 즐거움과 자연스러운 연결의 경험으로 전환해, 대기 순간도 축제의 일부가 되도록 만드는 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1TiIXER_SdvIXl3OGHQUOoIaCyqSE9HRH/view?usp=sharing',
    gitOrgUrl: 'https://github.com/PLINK-BACKEND',
    gitBeUrl: 'https://github.com/PLINK-BACKEND/PLINK-BACKEND',
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1308',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/BGBG.png`,
    title: '바구바구',
    teamMember: '김민서(PM) 외 5명',
    summary: '바로 구매하는 간편 장보기 체크리스트',
    description:
      '체크리스트 관리, 재고 연동 관리, AI 장보기 품목 추천, AI 장보기 소비 리포트 등의 기능을 통해 유저의 보다 편리하고 즐거운 장보기 생활을 지원하는 서비스',
    googleDriveUrl: 'https://drive.google.com/file/d/1Bs5JY0G4Fem93bkccEkfpd_46kE0NksH/view?usp=sharing',
    gitOrgUrl: 'https://github.com/4thon-BGBG',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1309',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/kkambbaki.png`,
    title: '깜빡이',
    teamMember: '김보민(BE) 외 5명',
    summary: '숨겨진 집중력의 불을 켜주는 아동교육 서비스',
    description:
      'ADHD 아동의 집중력 향상을 목표로 하는 아동 교육 서비스입니다. 인지력 샹항을 위한 뿅뿅 아기별 게임과 충동 조절을 위한 꼬마 교통지킴이 게임으로 구성되어 있습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1vReoGD0CVAdn-5DrXiJqvtp-JWjawom6/view?usp=sharing',
    gitOrgUrl: 'https://github.com/kkambbaki',
    gitBeUrl: 'https://github.com/kkambbaki/backend',
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Django, Next.js(TypeScript)',
    award: null,
  },
  {
    id: '1310',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/crux.png`,
    title: 'CRUX',
    teamMember: '하지민(PM) 외 4명',
    summary: '대화를 흩날리지 말고 자산화하세요',
    description:
      '사용자가 LLM에게 질문하며 쌓인 대화를 자동으로 분석해, 핵심 개념·오해 포인트·다음 학습 과제를 한 장의 학습 리포트로 정리해주는 서비스입니다.\n흩어진 질문 기록을 구조화해 “내가 뭘 배웠고, 뭐가 부족한지”를 명확히 보여주고, 복습과 성장 루틴을 쉽게 만듭니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1lBgX_w420BrgIAzZmuvsKFp3uunJaSb2/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/nnaX000/4th_thon',
    gitFeUrl: 'https://github.com/Line4thon-team8/2025_Line4thon_team8_frontend',
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1311',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/altong.png`,
    title: '알통',
    teamMember: '이혜지(BE) 외 5명',
    summary: '알바생 교육부터 알바생 관리까지 책임지는 알바 통합 관리 플랫폼',
    description:
      '교육 매뉴얼, 퀴즈, 카드뉴스 생성을 통해 반복되는 알바 교육을 AI로 자동화하고, 출퇴근과 스케줄 관리까지 함께 제공하는 알바 운영 통합 플랫폼입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1fwgGAl6zCYjOe71ET8VhojbeYuzGgTmd/view?usp=sharing',
    gitOrgUrl: 'https://github.com/Line4thon-Altong',
    gitBeUrl: 'https://github.com/Line4thon-Altong/Altong-BE',
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(TypeScript)',
    award: null,
  },
  {
    id: '1312',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/FinForU.png`,
    title: 'FinForU',
    teamMember: '김은지(PM) 외 5명',
    summary:
      '외국인을 위한 AI 기반 맞춤 안내와 은행 연결을 통해 복잡한 제도 환경의 접근성을 높이는 스마트 동반자 서비스',
    description:
      '국내 금융 환경에 익숙하지 않은 외국인을 위한 AI 기반 다국어 금융 안내 서비스입니다.\nAI 대화형 챗봇을 통해 예·적금과 카드 상품 탐색, 외국인 이용 가능 은행·점포 정보, 환율 정보를 다국어로 제공해 금융 의사결정을 지원합니다.\n복잡한 금융 정보를 대화로 쉽게 이해할 수 있도록 설계해 외국인의 안정적인 금융 생활 정착을 돕습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1LDEDgUtAgNMiokUI8Pwt6iNTK4JuDCwT/view?usp=sharing',
    gitOrgUrl: 'https://github.com/line4thon-team10',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1313',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/knit.png`,
    title: 'Knit',
    teamMember: '이승채(FE) 외 5명',
    summary: '가장 가까운 존재, 대화로 엮어내는 가족 이야기',
    description:
      'KNIT는 실을 잇듯이 가족의 생각·감정·이야기를 이어, 하나의 관계를 함께 짜 나가는 서비스입니다. 오늘의 질문, 가족 미션, Q&A 카드, 캐릭터 키우기, 추억 보관함을 통해 매일의 작은 대화가 쌓여 가족이 더 단단하고 따뜻해지도록 돕습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1lAX5jJTUC9SijLQJ0gkj_4lFFk2WYvpq/view?usp=sharing',
    gitOrgUrl: 'https://github.com/knit2025',
    gitBeUrl: null,
    gitFeUrl: 'https://github.com/knit2025/KNIT-FE',
    no: '13기',
    category: '4호선톤',
    techStack: 'Django, React(TypeScript)',
    award: null,
  },
  {
    id: '1314',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/Challink.png`,
    title: 'Challink',
    teamMember: '정교은(FE) 외 5명',
    summary: 'AI 검증 기반 참여형 챌린지 공유 서비스',
    description:
      'AI가 챌린지 인증의 신뢰를 지켜주는 플랫폼. 친구들과 함께 공정하게 경쟁하고, 끝까지 목표를 달성하는 경험을 제공합니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1D1a_1hqJ_ccDdXxOFW6GT2CuUGR3PljM/view?usp=sharing',
    gitOrgUrl: 'https://github.com/Likelion13-line4-Challink',
    gitBeUrl: null,
    gitFeUrl: 'https://github.com/Likelion13-line4-Challink/Challink-FE',
    no: '13기',
    category: '4호선톤',
    techStack: 'Django, React(JavaScript)',
    award: null,
  },
  {
    id: '1315',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/qroom.png`,
    title: 'Qroom',
    teamMember: '이채빈(FE) 외 4명',
    summary: '같이 문제 내고, 같이 성장하는 공간',
    description:
      '같은 수업을 듣는 학생들과 그룹을 형성하여 AI와 함께 시험 준비까지 책임지는 AI 기반 대학생 그룹 스터디 웹 서비스',
    googleDriveUrl: 'https://drive.google.com/file/d/1lB8QPTM9Q7SwdMM0tQYsNPA9IEd9xc1M/view?usp=sharing',
    gitOrgUrl: 'https://github.com/Line4thon-Qroom',
    gitBeUrl: null,
    gitFeUrl: 'https://github.com/Line4thon-Qroom/FE',
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(TypeScript)',
    award: null,
  },
  {
    id: '1316',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/TomoLow.png`,
    title: 'TomoLow',
    teamMember: '박소연(FE)\n 이경은(BE) 외 4명',
    summary: 'AI 기반 모의투자 학습 서비스',
    description:
      '실시간 가상화폐 시세를 기반으로 사용자가 챗봇 학습과 모의투자를 통해 직접 투자 경험을 쌓을 수 있도록 돕는 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1zqkZs-xfrBW90T8DjD7hyHoTFoYANaVJ/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/line4-hackathon/tomolow-be',
    gitFeUrl: 'https://github.com/line4-hackathon/tomolow-fe',
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(TypeScript)',
    award: null,
  },
  {
    id: '1317',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/ExpertOfOrdering.png`,
    title: '주문의 달인',
    teamMember: '김민서(PM)\n이승채(FE), 이연서(FE)\n김보민(BE), 최서아(BE)',
    summary: '실버 세대를 위한 키오스크 주문 연습 시뮬레이션',
    description:
      '키오스크 주문에 어려움을 겪는 분들을 위해, 집에서도 실제 키오스크 환경을 그대로 체험하며 연습할 수 있도록 돕는 자가 시뮬레이션 서비스입니다. 난이도 설정을 통해 간단한 주문부터 다양한 옵션 선택이 필요한 상황까지 단계적으로 반복 학습할 수 있습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/18wXsrPOyApgzQBFfVfLf54ZVhk4lqDMP/view?usp=sharing',
    gitOrgUrl: 'https://github.com/ExpertOfOrdering',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '파이널프로젝트',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1318',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/careLink.png`,
    title: 'CareLink',
    teamMember: '김은지(PM)\n박소연(FE), 이채빈(FE)\n안성민(BE), 이경은(BE)',
    summary: '건강과 일상을 챙기는 새로운 치매 관리 플랫폼',
    description:
      '치매 관리가 일상 속에서 자연스럽게 이루어지도록 설계된 플랫폼입니다.\n복약·일정 관리, 음성 기반 체크인, 인지훈련 콘텐츠를 제공하고 보호자에게는 상태 요약을 전달해 지속 가능한 관리 구조를 만듭니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1G6xP0ZHNfKaG7f8tjdivB-WU7_InXEmi/view?usp=sharing',
    gitOrgUrl: 'https://github.com/final-project-likelion',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '파이널프로젝트',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1319',
    thumbnail: `${THIRTEENTH_PROJECT_IMAGE_PATH}/slowflow.png`,
    title: 'SlowFlow',
    teamMember: '하지민(PM)\n박세은(FE), 정교은(FE)\n이혜지(BE)',
    summary: '완벽하지 않아도 괜찮은 저속노화 관리법',
    description:
      "단순한 식단을 넘어 생활 습관 전반의 노화 속도를 측정합니다. 오늘 쌓인 채움(노화 방지)과 부담(가속 요인) 점수를 기록하고, AI의 분석을 통해 더 느리고 건강하게 늙어가는 '저속노화 라이프'를 설계해 보세요.",
    googleDriveUrl: 'https://drive.google.com/file/d/1bxu2XcFUx_ftBWAzs7lK4r_fS0nWon_t/view?usp=sharing',
    gitOrgUrl: 'https://github.com/Likelion-final-SlowFlow',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '파이널프로젝트',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
];
