const THIRTEENTH_PROJECT_IMAGE_PATH = import.meta.env.VITE_LOCAL_IMAGE_PATH + '/project/13th';

export const thirteenthProjectsData = [
  {
    id: '1300',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/neonnaekkeoGYM/neonnaekkeoGYM.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/neonnaekkeoGYM/neonnaekkeoGYM1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/neonnaekkeoGYM/neonnaekkeoGYM2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/neonnaekkeoGYM/neonnaekkeoGYM3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/neonnaekkeoGYM/neonnaekkeoGYM4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/neonnaekkeoGYM/neonnaekkeoGYM5.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/neonnaekkeoGYM/neonnaekkeoGYM6.png`,
    ],
    title: '넌내꺼짐',
    teamMember: '하지민(PM)\n박소연(FE), 이승채(FE)\n안성민(BE), 이혜지(BE)',
    summary: '기구 앞 눈치싸움에서 벗어나는 가장 똑똑한 방법',
    description:
      '헬스장 및 기구별 혼잡도와 개인 운동 루틴을 고려해, AI가 효율적인 기구 사용 순서를 자동으로 배정하여 운동 흐름이 끊기지 않도록 돕는 헬스장 배정 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1CFuPEeZwHHMtR4-XNJSfcY7JZwjsTu-U/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '아이디어톤',
    techStack: '-',
    award: null,
  },
  {
    id: '1301',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/balpyoHAI/balpyoHAI.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/balpyoHAI/balpyoHAI1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/balpyoHAI/balpyoHAI2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/balpyoHAI/balpyoHAI3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/balpyoHAI/balpyoHAI4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/balpyoHAI/balpyoHAI5.png`,
    ],
    title: '발표HAI',
    teamMember: '김은지(PM)\n이채빈(FE), 정교은(FE)\n김보민(BE)',
    summary: '발표가 두려운 순간, 당신만을 위한 AI 발표 튜터',
    description:
      '발표HAI는 발표가 두려운 학생을 위한 AI 발표 튜터링 서비스입니다. 발표 유형별 맞춤 분석과 실시간 피드백으로 제공하여 발표 흐름과 전달력을 개선에 도움을 줍니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1EwiAyHiHS88qwNwXx7KmXgm5GQbH1sF9/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '아이디어톤',
    techStack: '-',
    award: null,
  },
  {
    id: '1302',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/wearther/wearther.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/wearther/wearther1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/wearther/wearther2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/wearther/wearther3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/wearther/wearther4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/ideathon/wearther/wearther5.png`,
    ],
    title: 'WEARTHER',
    teamMember: '김민서(PM)\n박세은(FE), 이연서(FE)\n이경은(BE), 최서아(BE)',
    summary: '나만의 날씨 기반 코디네이터',
    description:
      '실제 내 옷장의 아이템을 기반으로 유저의 취향/상황과 현재 날씨에 맞게 코디를 추천해주는 AI 코디네이터 서비스',
    googleDriveUrl: 'https://drive.google.com/file/d/1Dt4xmoeZVs8Ay4J3xj8L146fMnWjqEyT/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '아이디어톤',
    techStack: '-',
    award: null,
  },
  {
    id: '1303',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Sasangsai/Sasangsai.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Sasangsai/Sasangsai1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Sasangsai/Sasangsai2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Sasangsai/Sasangsai3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Sasangsai/Sasangsai4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Sasangsai/Sasangsai5.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Sasangsai/Sasangsai6.png`,
    ],
    title: '사상사이',
    teamMember: '이연서(FE) 외 5명',
    summary:
      '조금은 민감할 수 있지만 열린 마음으로 함께 사회적으로 중요한 이슈를 학습하고 토론할 수 있는 플랫폼, 사상사이',
    description:
      '사상사이는 정치·젠더 등 민감하지만 중요한 사회 이슈를 전문가 아티클 큐레이션으로 쉽게 학습하고, 논제에 대해 투표·댓글로 다양한 관점을 토론하며, AI 리서치 도구로 신뢰할 수 있는 근거를 빠르게 찾아 설득력 있게 표현하고, 투표 결과를 바탕으로 정책 논의·제안까지 이어갈 수 있게 하는 토론형 SNS 플랫폼입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1CeMgV_3qHxGG_LlRLs8lo7tZeiD4xTFv/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-1',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: '최우수상',
  },
  {
    id: '1304',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Univearth/Univearth.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Univearth/Univearth1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Univearth/Univearth2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Univearth/Univearth3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Univearth/Univearth4.png`,
    ],
    title: 'Univearth',
    teamMember: '이경은(BE) 외 5명',
    summary: '캠퍼스 환경을 지키는 첫걸음, Univearth',
    description:
      '유니버스는 대학(원)생들이 퀴즈, 그룹 챌린지, 친환경 상점 공유를 통해 환경 문제 해결에 참여하고, 캠퍼스 대항전을 통해 지속적인 실천을 이어갈 수 있도록 돕는 친환경 활동 플랫폼입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1xDcc5wXhXY3hBD3RnDnO5AARkNvHc3Jw/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-2',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1305',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/HERizon_1305/HERizon.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/HERizon_1305/HERizon1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/HERizon_1305/HERizon2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/HERizon_1305/HERizon3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/HERizon_1305/HERizon4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/HERizon_1305/HERizon5.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/HERizon_1305/HERizon6.png`,
    ],
    title: 'HERizon',
    teamMember: '최서아(BE) 외 5명',
    summary: '여성 사용자의 STEM 관심사를 기반으로 직무-역량-롤모델을 연결하는 커리어 탐색 플랫폼',
    description:
      '여성 진출이 부족한 STEM분야에 10-20대 여성들이 자신의 관심사를 STEM진로와 쉽게 연결할 수 있도록 도와주는 입문자 친화적인 진로 탐색 큐레이션 서비스 입니다.',
    googleDriveUrl: 'https://drive.google.com/drive/u/0/folders/13gSpO8bMPyue-et_IQJpSQcABaem6SeW',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-3',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1306',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/MOODYA/MOODYA.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/MOODYA/MOODYA1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/MOODYA/MOODYA2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/MOODYA/MOODYA3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/MOODYA/MOODYA4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/MOODYA/MOODYA5.png`,
    ],
    title: 'MOODYA',
    teamMember: '하지민(PM) 외 5명',
    summary: '혼자 있는 시간도, 나를 여행하는 시간으로',
    description:
      '여성 혼자 있는 시간 속에서 자신의 감정을 돌아보고, 현재의 감정과 혼자 활동 역량에 맞는 안전한 힐링 장소와 코스를 추천해주는 감정 기반 솔로 힐링 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1zc_eKfNKNQMdWyHqjBxy5cmRWreU82dL/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-4',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1307',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Genteracy/Genteracy.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Genteracy/Genteracy1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Genteracy/Genteracy2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Genteracy/Genteracy3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Genteracy/Genteracy4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Genteracy/Genteracy5.png`,
    ],
    title: '젠터러시',
    teamMember: '이채빈(FE) 외 5명',
    summary: '최초의 페미니즘 마이크로러닝 플랫폼',
    description:
      '소셜 미디어의 한계를 넘어, 신뢰할 수 있는 엄선된 자료를 기반으로 언제 어디서든 쉽고 재미있게 페미니즘을 학습하고, 다양한 관점을 탐색하여 유연한 사고를 키울 수 있도록 돕는 페미니즘 마이크로 러닝 서비스를 기획 및 개발하였습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1CG4WHHupFrEap7EkOZFSFuyGVL2IdFSj/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-5',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1308',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Oopise/Oopise.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Oopise/Oopise1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Oopise/Oopise2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Oopise/Oopise3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Oopise/Oopise4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Oopise/Oopise5.png`,
    ],
    title: 'Oopsie',
    teamMember: '안성민(BE) 외 4명',
    summary: '실수하고, 망하고, 다시 일어서는 이야기들이 모이는 곳, Oopsie',
    description:
      '성공보다 실패가 주는 배움을 기록하는 실패담 공유 커뮤니티입니다. 카테고리별 실패 경험과 함께, 다시 선택할 수 있다면 무엇을 바꾸고 싶은지를 공유하며 공감과 성찰, 그리고 더 나은 선택을 나눕니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1CIyQ_ULV60KBLrFvCU2RX9bLFmBVhHdh/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-6',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: '우수상',
  },
  {
    id: '1309',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Myworkher/Myworkher.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Myworkher/Myworkher1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Myworkher/Myworkher2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Myworkher/Myworkher3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Myworkher/Myworkher4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Myworkher/Myworkher5.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Myworkher/Myworkher6.png`,
    ],
    title: '마이워커',
    teamMember: '김민서(PM) 외 4명',
    summary: '당신을 위한 여성 전문가',
    description: '기존에 불편을 겪던 분야나 여성 특화 분야에서 여성 고객이 여성 전문가를 매칭받을 수 있는 서비스',
    googleDriveUrl: 'https://drive.google.com/file/d/1vdX0qAfWfwJQe8a5xDUbCf0RmLZPVrbX/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-9',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: '특별상',
  },
  {
    id: '1310',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Dearbebe/Dearbebe.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Dearbebe/Dearbebe1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Dearbebe/Dearbebe2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Dearbebe/Dearbebe3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Dearbebe/Dearbebe4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Dearbebe/Dearbebe5.png`,
    ],
    title: 'Dearbebe',
    teamMember: '이혜지(BE) 외 4명',
    summary: '소중한 우리 아이를 위한 따뜻한 나눔 공간',
    description:
      '더 이상 사용하지 않는 육아용품을 필요로 하는 이웃과 쉽게 나누고 교환할 수 있는 공간으로, 복잡한 흥정이나 가격 경쟁 없이 육아용품을 효율적으로 순환시키는 거래 플랫폼입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1giOfCYVr4MKYCbQGCTYRXUKuXMS45Hgy/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-12',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1311',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Nexit/Nexit.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Nexit/Nexit1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Nexit/Nexit2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Nexit/Nexit3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Nexit/Nexit4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Nexit/Nexit5.png`,
    ],
    title: '넥시트',
    teamMember: '이승채(FE) 외 4명',
    summary: "다음을 향한 탈출구, N:EXIT - '폭력의 인식'을 시작으로, 탈출까지 연결되는 서비스",
    description:
      'N:EXIT는 데이트폭력 피해자가 관계 속 위험을 인식하고, 증거와 상황을 정리하고, 유사 경험자들과의 정보 공유를 통해 다음으로 나아갈 수 있도록 돕는 증거기록 - 경험 공유 - 자가진단 기반의 통합 지원 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/13otCWVYN7TCNwXHiABIsA5-tjGT3z2A1/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-14',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1312',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/FastER/FastER.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/FastER/FastER1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/FastER/FastER2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/FastER/FastER3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/FastER/FastER4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/FastER/FastER5.png`,
    ],
    title: 'FastER+',
    teamMember: '박세은(FE) 외 4명',
    summary: '병원 찾기부터 도착까지, 함께하는 FastER',
    description:
      '갑작스러운 병원 방문 시, 가장 빠르게 진료 가능한 병원을 실시간으로 안내하는 모바일 웹 기반 병원 안내 서비스. FastER는 단순한 병원 정보 서비스가 아닙니다. 사용자의 긴급 상황을 함께 해결해주는 "디지털 의료 동반자"입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1AAp_sj4r3V4594IF1qCOeUexLH709uiU/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-15',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1313',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/EraEcho/EraEcho.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/EraEcho/EraEcho1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/EraEcho/EraEcho2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/EraEcho/EraEcho3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/EraEcho/EraEcho4.png`,
    ],
    title: 'EraEcho',
    teamMember: '정교은(FE) 외 4명',
    summary:
      '잊혀진 여성 인물의 이야기를 탐험하고, 퀴즈로 즐겁게 배우며, 학교별 랭킹으로 참여를 유도하는 인터랙티브 역사 체험 플랫폼',
    description:
      'EraEcho는 잊힌 여성 인물들의 이야기를 카드, 퀴즈, 커뮤니티라는 일상적인 포맷으로 구성하여 사용자가 쉽게 접하고, 자연스럽게 상호작용할 수 있도록 설계된 플랫폼이에요',
    googleDriveUrl: 'https://drive.google.com/file/d/1EVjysaTSkAEVvCQ3wlFYAtpesV6_iLqF/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-17',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1314',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Herizon_1314/Herizon.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Herizon_1314/Herizon1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Herizon_1314/Herizon2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Herizon_1314/Herizon3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Herizon_1314/Herizon4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Herizon_1314/Herizon5.png`,
    ],
    title: 'Herizon',
    teamMember: '김은지(PM/PD)외 4명',
    summary: '멘토링과 커뮤니티를 통해 경험을 나누며, 함께 성장하는 경력 단절 여성 재취업 지원 플랫폼입니다.',
    description:
      '경력 단절로 혼자 다시 시작하기 어려운 여성들이 멘토와 연결되어 재취업을 준비할 수 있도록 돕는 플랫폼입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1QKRsntUmL_z50yhz9muvY6dx_SxL1fbg/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-19',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1315',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Took/Took.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Took/Took1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Took/Took2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Took/Took3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Took/Took4.png`,
    ],
    title: '툭(Took)',
    teamMember: '박소연(FE) 외 4명',
    summary: '여성들의 고민을 있는 그대로, 툭: 여성 건강 상담 서비스',
    description:
      '10·20대를 위한 여성 건강 상담 서비스로, 올바른 성 지식과 정서적 지원을 동시에 제공하며 여성 건강 관련 질문을 익명으로 편하게 나눌 수 있는 온라인 공간입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1PwMutg5JJxgleyuKibLh2PgPyqE4bKkW/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-20',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1316',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Teumteum/Teumteum.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Teumteum/Teumteum1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Teumteum/Teumteum2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Teumteum/Teumteum3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Teumteum/Teumteum4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/herethon/Teumteum/Teumteum5.png`,
    ],
    title: '틈틈(TeumTeum)',
    teamMember: '김보민(BE) 외 4명',
    summary: '단절의 시간을 기회의 시간으로 바꾸는 여성 취업지원 서비스',
    description:
      '경력단절 여성들의 재취업을 돕는 커뮤니티입니다. 취업 정보를 공유하고, 서로 정서적인 지지를 얻을 수 있습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1V_eNrEReP2aVpINqFHvzrt0saAH5uU3V/view?usp=sharing',
    gitOrgUrl: 'https://github.com/2025-HERETHON/2025-herethon-22',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '여기톤',
    techStack: 'Django, HTML, CSS, JavaScript',
    award: null,
  },
  {
    id: '1317',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/spotal/spotal.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/spotal/spotal1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/spotal/spotal2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/spotal/spotal3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/spotal/spotal4.png`,
    ],
    title: 'Spotal',
    teamMember: '하지민(PM)\n박세은(FE), 이연서(FE)\n김보민(BE), 안성민(BE)\n최서아(BE)',
    summary: '가게의 흔적과 기억을 연결하는 동네의 감성 기록장',
    description:
      '재개발로 사라진 동네 가게와 그에 얽힌 기억을 기록하고,\n사용자의 감성을 기준으로 유사한 새로운 공간을 연결해주는 AI 기반 장소 아카이빙 서비스입니다.\n잊힌 공간의 이야기를 보존하며, 단골과 동네 상권을 다시 이어줍니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1z3DW2ZiMCGFkeYnb5WE6VbZ2KHPBOSNL/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/Likelion-at-SMWU-13th/Spotal-BE',
    gitFeUrl: 'https://github.com/Likelion-at-SMWU-13th/Spotal-FE',
    no: '13기',
    category: '중앙해커톤',
    techStack: 'Django, React(JavaScript)',
    award: null,
  },
  {
    id: '1318',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/gorugoru/gorugoru.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/gorugoru/gorugoru1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/gorugoru/gorugoru2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/gorugoru/gorugoru3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/gorugoru/gorugoru4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/gorugoru/gorugoru5.png`,
    ],
    title: 'GoruGoru',
    teamMember: '김은지(PM)\n박소연(FE), 정교은(FE)\n이경은(BE), 이혜지(BE)',
    summary: '외국인 여행객과 상인을 이어주는 다국어 전통시장 탐방 플랫폼',
    description:
      '언어와 정보의 장벽으로 접근이 어려웠던 전통시장을 외국인 여행객이 쉽게 이해하고 탐방할 수 있도록 돕는 서비스입니다.\n상점 정보와 코스 추천을 통해 이용 맥락을 직관적으로 제공해 전통시장 이용 경험을 확장하고, 여행객과 상인 간의 자연스러운 교류를 만들어냅니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1QQ28vVPt_eIh-LNXjo8uJRzdG5HZZunh/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/Likelion-at-SMWU-13th/OnDongNae-Server',
    gitFeUrl: 'https://github.com/Likelion-at-SMWU-13th/OnDongNae-Client',
    no: '13기',
    category: '중앙해커톤',
    techStack: 'Django, React(JavaScript)',
    award: null,
  },
  {
    id: '1319',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/tumblerin/tumblerin.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/tumblerin/tumblerin1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/tumblerin/tumblerin2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/hackathon/tumblerin/tumblerin3.png`,
    ],
    title: '텀블러인',
    teamMember: '김민서(PM)\n이승채(FE), 이채빈(FE)\n서문지(BE), 이현정(BE), 홍상희(BE)',
    summary: '함께 만드는 우리 동네 텀블러 문화',
    description:
      '텀블러인은 우리 동네 카페와 함께 텀블러 이용 문화를 확산하는 친환경 서비스입니다. 텀블러 혜택 카페 정보와 맞춤형 추천을 제공하고, 텀블러 인증을 통해 스탬프·포인트 적립과 할인 혜택을 받을 수 있도록 합니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1-kGrarxELvMYl43lTdtWIvD6pDvUfCxS/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/Likelion-at-SMWU-13th/Tumbloom-BE',
    gitFeUrl: 'https://github.com/Likelion-at-SMWU-13th/Tumbloom-FE',
    no: '13기',
    category: '중앙해커톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1320',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/cooltime/cooltime.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/cooltime/cooltime1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/cooltime/cooltime2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/cooltime/cooltime3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/cooltime/cooltime4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/cooltime/cooltime5.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/cooltime/cooltime6.png`,
    ],
    title: '쿨타임',
    teamMember: '박세은(FE), 이연서(FE) 외 3명',
    summary: '미룸을 기록하고 나를 이해하는 회복형 서비스',
    description:
      '쿨타임(COOLTIME)은 미룸(지연행동)을 기록해 원인과 패턴을 파악하고, 유형 테스트와 AI 주간 레포트로 맞춤 피드백을 제공해 자기 회복을 돕는 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1_4nfDTBxk4lRTfEikidfs6B3VaOKiqiN/view?usp=sharing',
    gitOrgUrl: 'https://github.com/4LINETHON-Team1',
    gitBeUrl: null,
    gitFeUrl: 'https://github.com/4LINETHON-Team1/Cooltime-FE',
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1321',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/plink/plink.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/plink/plink1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/plink/plink2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/plink/plink3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/plink/plink4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/plink/plink5.png`,
    ],
    title: 'PLINK',
    teamMember: '안성민(BE), 최서아(BE) 외 4명',
    summary: '축제의 지루한 대기 시간을 함께 즐기는 놀이(Play)로 연결(Link)하는 서비스',
    description:
      'PLINK는 축제에서 지루한 기다림 시간을 즉각적인 즐거움과 자연스러운 연결의 경험으로 전환해, 대기 순간도 축제의 일부가 되도록 만드는 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1TiIXER_SdvIXl3OGHQUOoIaCyqSE9HRH/view?usp=sharing',
    gitOrgUrl: 'https://github.com/PLINK-BACKEND',
    gitBeUrl: 'https://github.com/PLINK-BACKEND/PLINK-BACKEND',
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: '우수상',
  },
  {
    id: '1322',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/BGBG/BGBG.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/BGBG/BGBG1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/BGBG/BGBG2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/BGBG/BGBG3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/BGBG/BGBG4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/BGBG/BGBG5.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/BGBG/BGBG6.png`,
    ],
    title: '바구바구',
    teamMember: '김민서(PM) 외 5명',
    summary: '바로 구매하는 간편 장보기 체크리스트',
    description:
      '체크리스트 관리, 재고 연동 관리, AI 장보기 품목 추천, AI 장보기 소비 리포트 등의 기능을 통해 유저의 보다 편리하고 즐거운 장보기 생활을 지원하는 서비스',
    googleDriveUrl: 'https://drive.google.com/file/d/1Bs5JY0G4Fem93bkccEkfpd_46kE0NksH/view?usp=sharing',
    gitOrgUrl: 'https://github.com/4thon-BGBG',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1323',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/kkambbaki/kkambbaki.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/kkambbaki/kkambbaki1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/kkambbaki/kkambbaki2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/kkambbaki/kkambbaki3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/kkambbaki/kkambbaki4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/kkambbaki/kkambbaki5.png`,
    ],
    title: '깜빡이',
    teamMember: '김보민(BE) 외 5명',
    summary: '숨겨진 집중력의 불을 켜주는 아동교육 서비스',
    description:
      'ADHD 아동의 집중력 향상을 목표로 하는 아동 교육 서비스입니다. 인지력 향상을 위한 뿅뿅 아기별 게임과 충동 조절을 위한 꼬마 교통지킴이 게임으로 구성되어 있습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1vReoGD0CVAdn-5DrXiJqvtp-JWjawom6/view?usp=sharing',
    gitOrgUrl: 'https://github.com/kkambbaki',
    gitBeUrl: 'https://github.com/kkambbaki/backend',
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Django, Next.js(TypeScript)',
    award: null,
  },
  {
    id: '1324',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/crux/crux.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/crux/crux1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/crux/crux2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/crux/crux3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/crux/crux4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/crux/crux5.png`,
    ],
    title: 'CRUX',
    teamMember: '하지민(PM) 외 4명',
    summary: '대화를 흩날리지 말고 자산화하세요',
    description:
      '사용자가 LLM에게 질문하며 쌓인 대화를 자동으로 분석해, 핵심 개념·오해 포인트·다음 학습 과제를 한 장의 학습 리포트로 정리해주는 서비스입니다.\n흩어진 질문 기록을 구조화해 “내가 뭘 배웠고, 뭐가 부족한지”를 명확히 보여주고, 복습과 성장 루틴을 쉽게 만듭니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1lBgX_w420BrgIAzZmuvsKFp3uunJaSb2/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/nnaX000/4th_thon',
    gitFeUrl: 'https://github.com/Line4thon-team8/2025_Line4thon_team8_frontend',
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: '특별상',
  },
  {
    id: '1325',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/altong/altong.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/altong/altong1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/altong/altong2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/altong/altong3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/altong/altong4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/altong/altong5.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/altong/altong6.png`,
    ],
    title: '알통',
    teamMember: '이혜지(BE) 외 5명',
    summary: '알바생 교육부터 알바생 관리까지 책임지는 알바 통합 관리 플랫폼',
    description:
      '교육 매뉴얼, 퀴즈, 카드뉴스 생성을 통해 반복되는 알바 교육을 AI로 자동화하고, 출퇴근과 스케줄 관리까지 함께 제공하는 알바 운영 통합 플랫폼입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1fwgGAl6zCYjOe71ET8VhojbeYuzGgTmd/view?usp=sharing',
    gitOrgUrl: 'https://github.com/Line4thon-Altong',
    gitBeUrl: 'https://github.com/Line4thon-Altong/Altong-BE',
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(TypeScript)',
    award: null,
  },
  {
    id: '1326',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/FinForU/FinForU.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/FinForU/FinForU1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/FinForU/FinForU2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/FinForU/FinForU3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/FinForU/FinForU4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/FinForU/FinForU5.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/FinForU/FinForU6.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/FinForU/FinForU7.png`,
    ],
    title: 'FinForU',
    teamMember: '김은지(PM) 외 5명',
    summary:
      '외국인을 위한 AI 기반 맞춤 안내와 은행 연결을 통해 복잡한 제도 환경의 접근성을 높이는 스마트 동반자 서비스',
    description:
      '국내 금융 환경에 익숙하지 않은 외국인을 위한 AI 기반 다국어 금융 안내 서비스입니다.\nAI 대화형 챗봇을 통해 예·적금과 카드 상품 탐색, 외국인 이용 가능 은행·점포 정보, 환율 정보를 다국어로 제공해 금융 의사결정을 지원합니다.\n복잡한 금융 정보를 대화로 쉽게 이해할 수 있도록 설계해 외국인의 안정적인 금융 생활 정착을 돕습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1LDEDgUtAgNMiokUI8Pwt6iNTK4JuDCwT/view?usp=sharing',
    gitOrgUrl: 'https://github.com/line4thon-team10',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1327',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/knit/knit.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/knit/knit1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/knit/knit2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/knit/knit3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/knit/knit4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/knit/knit5.png`,
    ],
    title: 'Knit',
    teamMember: '이승채(FE) 외 5명',
    summary: '가장 가까운 존재, 대화로 엮어내는 가족 이야기',
    description:
      'KNIT는 실을 잇듯이 가족의 생각·감정·이야기를 이어, 하나의 관계를 함께 짜 나가는 서비스입니다. 오늘의 질문, 가족 미션, Q&A 카드, 캐릭터 키우기, 추억 보관함을 통해 매일의 작은 대화가 쌓여 가족이 더 단단하고 따뜻해지도록 돕습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1lAX5jJTUC9SijLQJ0gkj_4lFFk2WYvpq/view?usp=sharing',
    gitOrgUrl: 'https://github.com/knit2025',
    gitBeUrl: null,
    gitFeUrl: 'https://github.com/knit2025/KNIT-FE',
    no: '13기',
    category: '4호선톤',
    techStack: 'Django, React(TypeScript)',
    award: null,
  },
  {
    id: '1328',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/Challink/Challink.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/Challink/Challink1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/Challink/Challink2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/Challink/Challink3.png`,
    ],
    title: 'Challink',
    teamMember: '정교은(FE) 외 5명',
    summary: 'AI 검증 기반 참여형 챌린지 공유 서비스',
    description:
      'AI가 챌린지 인증의 신뢰를 지켜주는 플랫폼. 친구들과 함께 공정하게 경쟁하고, 끝까지 목표를 달성하는 경험을 제공합니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1D1a_1hqJ_ccDdXxOFW6GT2CuUGR3PljM/view?usp=sharing',
    gitOrgUrl: 'https://github.com/Likelion13-line4-Challink',
    gitBeUrl: null,
    gitFeUrl: 'https://github.com/Likelion13-line4-Challink/Challink-FE',
    no: '13기',
    category: '4호선톤',
    techStack: 'Django, React(JavaScript)',
    award: null,
  },
  {
    id: '1329',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/qroom/qroom.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/qroom/qroom1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/qroom/qroom2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/qroom/qroom3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/qroom/qroom4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/qroom/qroom5.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/qroom/qroom6.png`,
    ],
    title: 'Qroom',
    teamMember: '이채빈(FE) 외 4명',
    summary: '같이 문제 내고, 같이 성장하는 공간',
    description:
      '같은 수업을 듣는 학생들과 그룹을 형성하여 AI와 함께 시험 준비까지 책임지는 AI 기반 대학생 그룹 스터디 웹 서비스',
    googleDriveUrl: 'https://drive.google.com/file/d/1lB8QPTM9Q7SwdMM0tQYsNPA9IEd9xc1M/view?usp=sharing',
    gitOrgUrl: 'https://github.com/Line4thon-Qroom',
    gitBeUrl: null,
    gitFeUrl: 'https://github.com/Line4thon-Qroom/FE',
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(TypeScript)',
    award: null,
  },
  {
    id: '1330',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/TomoLow/TomoLow.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/TomoLow/TomoLow1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/TomoLow/TomoLow2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/TomoLow/TomoLow3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/TomoLow/TomoLow4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/4linethon/TomoLow/TomoLow5.png`,
    ],
    title: 'TomoLow',
    teamMember: '박소연(FE)\n 이경은(BE) 외 4명',
    summary: 'AI 기반 모의투자 학습 서비스',
    description:
      '실시간 가상화폐 시세를 기반으로 사용자가 챗봇 학습과 모의투자를 통해 직접 투자 경험을 쌓을 수 있도록 돕는 서비스입니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1zqkZs-xfrBW90T8DjD7hyHoTFoYANaVJ/view?usp=sharing',
    gitOrgUrl: null,
    gitBeUrl: 'https://github.com/line4-hackathon/tomolow-be',
    gitFeUrl: 'https://github.com/line4-hackathon/tomolow-fe',
    no: '13기',
    category: '4호선톤',
    techStack: 'Spring Boot, React(TypeScript)',
    award: null,
  },
  {
    id: '1331',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/ExpertOfOrdering/ExpertOfOrdering.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/ExpertOfOrdering/ExpertOfOrdering1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/ExpertOfOrdering/ExpertOfOrdering2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/ExpertOfOrdering/ExpertOfOrdering3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/ExpertOfOrdering/ExpertOfOrdering4.png`,
    ],
    title: '주문의 달인',
    teamMember: '김민서(PM)\n이승채(FE), 이연서(FE)\n김보민(BE), 최서아(BE)',
    summary: '실버 세대를 위한 키오스크 주문 연습 시뮬레이션',
    description:
      '키오스크 주문에 어려움을 겪는 분들을 위해, 집에서도 실제 키오스크 환경을 그대로 체험하며 연습할 수 있도록 돕는 자가 시뮬레이션 서비스입니다. 난이도 설정을 통해 간단한 주문부터 다양한 옵션 선택이 필요한 상황까지 단계적으로 반복 학습할 수 있습니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/18wXsrPOyApgzQBFfVfLf54ZVhk4lqDMP/view?usp=sharing',
    gitOrgUrl: 'https://github.com/ExpertOfOrdering',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '파이널프로젝트',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1332',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/CareLink/CareLink.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/CareLink/CareLink1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/CareLink/CareLink2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/CareLink/CareLink3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/CareLink/CareLink4.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/CareLink/CareLink5.png`,
    ],
    title: 'CareLink',
    teamMember: '김은지(PM)\n박소연(FE), 이채빈(FE)\n안성민(BE), 이경은(BE)',
    summary: '건강과 일상을 챙기는 새로운 치매 관리 플랫폼',
    description:
      '치매 관리가 일상 속에서 자연스럽게 이루어지도록 설계된 플랫폼입니다.\n복약·일정 관리, 음성 기반 체크인, 인지훈련 콘텐츠를 제공하고 보호자에게는 상태 요약을 전달해 지속 가능한 관리 구조를 만듭니다.',
    googleDriveUrl: 'https://drive.google.com/file/d/1G6xP0ZHNfKaG7f8tjdivB-WU7_InXEmi/view?usp=sharing',
    gitOrgUrl: 'https://github.com/final-project-likelion',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '파이널프로젝트',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
  {
    id: '1333',
    images: [
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/slowflow/slowflow.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/slowflow/slowflow1.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/slowflow/slowflow2.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/slowflow/slowflow3.png`,
      `${THIRTEENTH_PROJECT_IMAGE_PATH}/finalproject/slowflow/slowflow4.png`,
    ],
    title: 'SlowFlow',
    teamMember: '하지민(PM)\n박세은(FE), 정교은(FE)\n이혜지(BE)',
    summary: '완벽하지 않아도 괜찮은 저속노화 관리법',
    description:
      "단순한 식단을 넘어 생활 습관 전반의 노화 속도를 측정합니다. 오늘 쌓인 채움(노화 방지)과 부담(가속 요인) 점수를 기록하고, AI의 분석을 통해 더 느리고 건강하게 늙어가는 '저속노화 라이프'를 설계해 보세요.",
    googleDriveUrl: 'https://drive.google.com/file/d/1bxu2XcFUx_ftBWAzs7lK4r_fS0nWon_t/view?usp=sharing',
    gitOrgUrl: 'https://github.com/Likelion-final-SlowFlow',
    gitBeUrl: null,
    gitFeUrl: null,
    no: '13기',
    category: '파이널프로젝트',
    techStack: 'Spring Boot, React(JavaScript)',
    award: null,
  },
];
